name: Assignment Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # Job 1: Provided test job
  test:
    name: Simple Hello Job
    runs-on: ubuntu-latest
    steps:
      - name: 23f3004255@ds.study.iitm.ac.in
        run: echo "Hello, world!"

  # 2: Check Python syntax if Python files exist
  python-syntax-check:
    name: Python Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find and check Python files
        run: |
          set -e
          echo "🔍 Searching for Python files..."
          
          # Find all .py files (recursively)
          python_files=$(find . -type f -name "*.py")
  
          if [ -z "$python_files" ]; then
            echo "No Python files found, skipping syntax check."
            exit 0
          fi
  
          echo "Found the following Python files:"
          echo "$python_files"
  
          # Check syntax for each file
          for file in $python_files; do
            echo "Checking syntax of $file"
            python3 -m py_compile "$file"
          done
  
          echo "All Python files passed syntax check."

